# Generated by Django 5.0.6 on 2024-05-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(upload_to='profile'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('ap_date', models.DateField()),
                ('address', models.TextField()),
                ('report', models.FileField(upload_to='profile')),
                ('dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
    ]
